### ISSUE TITLE
gzip.BadGzipFile: Not a gzipped file (b'<!') | pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by Cameron-Nguyen1** [churchmanlab/genewalk#75]
Hello, I am trying to use genewalk to help identify genes of interest as previously highlighted by DE analysis.
Thank you for reading this, please contact me for any additional information you all might need.

I have tried using a conda environment to install genewalk using python 3.12.x, 3.10.x, and 3.8.0.
At the bottom of the post is an example of my MGI file.

Here's my script I've been using to setup an env for genewalk.

conda create --name p38
conda activate p38
conda install --name p38 python=3.8.0
cd /root/anaconda3/envs/p38/bin
./pip install genewalk
genewalk --project EX --genes JustMGIid.txt --id_type=mgi_id

After running the script above for either of the three python versions listed, I receive these error in this order:
INFO: [2024-08-01 19:42:10] genewalk.cli - Saving into /root/genewalk/EX/genes.pkl...
INFO: [2024-08-01 19:42:10] genewalk.nx_mg_assembler - Adding gene edges from Pathway Commons to graph.
INFO: [2024-08-01 19:42:10] genewalk.resources - Downloading https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.All.hgnc.sif.gz and extracting into /root/genewalk/resources/PathwayCommons12.All.hgnc.sif
Traceback (most recent call last):
  File "/root/anaconda3/envs/p38/bin/genewalk", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/cli.py", line 157, in main
    run_main(args)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/cli.py", line 197, in run_main
    MG = load_network(args.network_source, args.network_file, genes,
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/nx_mg_assembler.py", line 36, in load_network
    mg = PcNxMgAssembler(genes, resource_manager=resource_manager)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/nx_mg_assembler.py", line 204, in __init__
    self.add_pc_edges()
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/nx_mg_assembler.py", line 212, in add_pc_edges
    gwn_df = pd.read_csv(self.resource_manager.get_pc(), sep='\t',
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/resources.py", line 44, in get_pc
    download_gz(fname, url_pc)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/resources.py", line 134, in download_gz
    shutil.copyfileobj(fin, fout)
  File "/root/anaconda3/envs/p38/lib/python3.8/shutil.py", line 202, in copyfileobj
    buf = fsrc_read(length)
  File "/root/anaconda3/envs/p38/lib/python3.8/gzip.py", line 286, in read
    return self._buffer.read(size)
  File "/root/anaconda3/envs/p38/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/root/anaconda3/envs/p38/lib/python3.8/gzip.py", line 473, in read
    if not self._read_gzip_header():
  File "/root/anaconda3/envs/p38/lib/python3.8/gzip.py", line 421, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'<!')

Which goes away after running the command again; however, the next error arises after resubmitting the final command written above.

INFO: [2024-08-01 19:42:16] genewalk.cli - Saving into /root/genewalk/EX/genes.pkl...
INFO: [2024-08-01 19:42:16] genewalk.nx_mg_assembler - Adding gene edges from Pathway Commons to graph.
INFO: [2024-08-01 19:42:17] genewalk.resources - Replacing outdated HGNC symbols in /root/genewalk/resources/PathwayCommons12.All.hgnc.sif and saving as /root/genewalk/resources/PathwayCommons12.All.hgnc_current.sif
Traceback (most recent call last):
  File "/root/anaconda3/envs/p38/bin/genewalk", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/cli.py", line 157, in main
    run_main(args)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/cli.py", line 197, in run_main
    MG = load_network(args.network_source, args.network_file, genes,
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/nx_mg_assembler.py", line 36, in load_network
    mg = PcNxMgAssembler(genes, resource_manager=resource_manager)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/nx_mg_assembler.py", line 204, in __init__
    self.add_pc_edges()
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/nx_mg_assembler.py", line 212, in add_pc_edges
    gwn_df = pd.read_csv(self.resource_manager.get_pc(), sep='\t',
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/resources.py", line 45, in get_pc
    self._replace_outdated_hgnc_symbols(fname,fname_current)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/genewalk/resources.py", line 94, in _replace_outdated_hgnc_symbols
    pc = pandas.read_csv(pc_old, sep='\t', dtype=str, header=None)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/root/anaconda3/envs/p38/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

My example MGI file:
MGI:1289196
MGI:88449
MGI:97809
MGI:1858510
MGI:1100492
MGI:2154244
MGI:96257
MGI:96646
MGI:107949
MGI:103178
MGI:105095
MGI:97796
MGI:98726
MGI:108571
MGI:2449923
MGI:1343124
MGI:97009

**Comment by ri23** [comment]
Hi @Cameron-Nguyen1 
Thanks for bringing this issue to our attention. We have fixed the error and released a new GeneWalk Python package v1.6.3.
To update to this latest version, please run in your environment:
`pip install --upgrade genewalk`
Then rerun:
`genewalk --project EX --genes JustMGIid.txt --id_type=mgi_id`
